### PR TITLE
Tickets/sitcom 1254

### PR DESCRIPTION
**Pull request by Kelks19**

### CODE REVIEW

**Review by bstalder — CHANGES_REQUESTED** [review]
I think you should indicate what specific dates the data analyses were made from as well as the dates the analyses were performed.  Many of these technotes should be updated with new data.

Also we should note which verifications are still pending to highlight future work.

**Comment by Kelks19** [comment]
I have made some changes to the layout, incorporating your feedback. This includes - 
1. index of the tests (only technotes so far) which will be linked to the respective sections within the page
2. the pending verifications include all the open SITCOM tickets I could find. 
3. Some the of SITCOM tickets which have primary results are already in the main body. 

The idea is to push the SITCOM tickets to the main body and ultimately to the top index as they progress /finalise. What do you think ? 

I was also thinking that at some point we might want to separate this technote into individual campaigns (based on the test data)

**Comment by bstalder** [comment]
sounds like great improvements.  is it ready to review?

**Comment by Kelks19** [comment]
Yes, it is ready to review.

**Review by bstalder — APPROVED** [review]
a few typographical errors, but good summary and formatting.

**Pull request merged**
